server:
  port: 9901
spring:
  application:
    name: maven-research-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maven-research-db?useSSL=false

    hikari:
      minimumIdle: 4
      idleTimeout: 600000
      maximumPoolSize: 8
      connectionTimeout: 30000
      maxLifetime: 1800000
grpc:
  port: 6570

dubbo:
  scan:
    base-packages: com.nghiatn.maven.controller.rpc.dubbo
  application:
    name: ${spring.application.name}



  registry:
    address: N/A
  provider:
    timeout: 9999
    protocols:
      -
        name: dubbo
        port: 8909
        serialization: hessian2
      -
        name: dubbo
        port: 8910
        serialization: protobuf



  consumer:
    timeout: 6666