server:
  port: 9900
spring:
  application:
    name: maven-research-service-client
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maven-research-db-client?useSSL=false

    hikari:
      minimumIdle: 4
      idleTimeout: 600000
      maximumPoolSize: 8
      connectionTimeout: 30000
      maxLifetime: 1800000

server-research:
  grpc:
    host: localhost
    port: 6570
dubbo:
  provider:
    timeout: 9999
  consumer:
    timeout: 6666
